Allow init without hacker address
hats-finance/ethical-return pull request #4
Opened 2023-01-04 17:53 UTC by ben-kaufman

2023-01-05 11:14 UTC, jellegerbrandy commented on contracts/EthicalReturn.sol
> +        if (hacker != address(0)) {
```suggestion
        if (hacker != address(0) && _hacker != hacker) 
```

2023-01-05 11:16 UTC, jellegerbrandy commented on contracts/EthicalReturn.sol
> +        if (hacker != address(0)) {
In this way the deposit function can be used twice

2023-01-05 11:17 UTC, jellegerbrandy requested changes
see the comment

2023-01-08 22:39 UTC, ben-kaufman commented on contracts/EthicalReturn.sol
> +        if (hacker != address(0)) {
Implemented a bit differently so the minimum amount isn't checked on extra deposits and the hacker isn't unnecessarily set.

2023-01-11 12:25 UTC, jellegerbrandy commented on contracts/EthicalReturn.sol
> +        if (hacker != address(0)) {
nice

2023-01-11 12:25 UTC, jellegerbrandy approved these changes

2023-01-11 12:25 UTC, merged